### PR TITLE
Date range labels

### PR DESCRIPTION
**Pull request by CharanMareedu-REISys**
## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Which browsers have you tested?
- [ ] Internet Explorer 11
- [ ] Edge
- [x] Chrome
- [x] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by CharanMareedu-REISys** [comment]
> Why are we now making that configurable? What change in requirement is this for?

We have a report where we need to display "From Created Date" instead of "From Date". Even though that is a small change and asked our PO if we can ignore it, he mentioned that is important as per business rules.

**Comment by CharanMareedu-REISys** [comment]
> > > Why are we now making that configurable? What change in requirement is this for?
> > 
> > 
> > We have a report where we need to display "From Created Date" instead of "From Date". Even though that is a small change and asked our PO if we can ignore it, he mentioned that is important as per business rules.
> 
> Why not use the the overall label that the component has to give context since that give the standard pattern for that component for the site.

We mentioned that to our PO and he insisted to make the changes instead of updating labels. 
Since we are modernizing the legacy FPDS and changing the label for that report will require user training as they are accustomed to it. I think we have support for labels with new version of data range component but since we have planned release of these reports to alpha and beta soon, we would require this change for sure.

**Comment by thomastighe** [comment]
> 
> 
> > > > Why are we now making that configurable? What change in requirement is this for?
> > > 
> > > 
> > > We have a report where we need to display "From Created Date" instead of "From Date". Even though that is a small change and asked our PO if we can ignore it, he mentioned that is important as per business rules.
> > 
> > 
> > Why not use the the overall label that the component has to give context since that give the standard pattern for that component for the site.
> 
> We mentioned that to our PO and he insisted to make the changes instead of updating labels.
> Since we are modernizing the legacy FPDS and changing the label for that report will require user training as they are accustomed to it. I think we have support for labels with new version of data range component but since we have planned release of these reports to alpha and beta soon, we would require this change for sure.

I had a conversation with Christy on this issue and she does not support this UI change. Until she does I will not approve this change. Her and Charles can come to agreement for this change.

**Comment by CharanMareedu-REISys** [comment]
> > > > > > Why are we now making that configurable? What change in requirement is this for?
> > > > > 
> > > > > 
> > > > > We have a report where we need to display "From Created Date" instead of "From Date". Even though that is a small change and asked our PO if we can ignore it, he mentioned that is important as per business rules.
> > > > 
> > > > 
> > > > Why not use the the overall label that the component has to give context since that give the standard pattern for that component for the site.
> > > 
> > > 
> > > We mentioned that to our PO and he insisted to make the changes instead of updating labels.
> > > Since we are modernizing the legacy FPDS and changing the label for that report will require user training as they are accustomed to it. I think we have support for labels with new version of data range component but since we have planned release of these reports to alpha and beta soon, we would require this change for sure.
> > 
> > 
> > I had a conversation with Christy on this issue and she does not support this UI change. Until she does I will not approve this change. Her and Charles can come to agreement for this change.
> 
> Thanks for the update Thomas. I will follow up with Charles.

This has been resolved with latest sam-ui version.

**Pull request closed without merging**
