### PR TITLE
adding alt tag for JAWS 17 508 compliance

### PR DESCRIPTION
**Pull request by dukeForsyth235**
Adding an "alt" Tag to the sam-actions-dropdown so that we can add specific text to the dropdown if the page we use them on contains multiple for JAWS 508 compliance.

### CODE REVIEW

**Comment by colinalford-gsa** [comment]
@dukeForsyth235 Did you run this issue by the designers? This seems like it might actually be a UX error. If we have multiple Download buttons on a page, it might make more sense to make the button text more descriptive in general.

Let me get confirmation from the designers that we want to change the download to be more specific text or if we want to just use the alt tag.

**Comment by dukeForsyth235** [comment]
@colinalford I didn't run this by the designers. 
I agree that if you changed the text for each button that would solve the issue but that would change the UI itself for everyone else, I wasn't sure if that was okay but asking someone on the design team is probably the right way to go.
Do you know who I can ask to get confirmation?

**Comment by colinalford-gsa** [comment]
@dukeForsyth235 Please contact Christy Hermansen, Kapil Grover, and Lorrin Harvey.

**Comment by dukeForsyth235** [comment]
Will do thanks!

**Pull request merged**
